version: '3.8'

services:
  import-service:
    build:
      context: .
      dockerfile: import-service/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./import-service/.env

  worker-service:
    build:
      context: .
      dockerfile: worker-service/Dockerfile
    env_file:
      - ./worker-service/.env

volumes:
  postgres_data:
