version: '3.8'

services:
  import-service:
    build:
      context: ./import-service
    ports:
      - "3000:3000"
    env_file:
      - ./import-service/.env
    volumes:
      - ./frontend:/app/../frontend

  worker-service:
    build:
      context: ./worker-service
    env_file:
      - ./worker-service/.env

volumes:
  postgres_data:
